[simulation]
seeds = [
    1, 2, 5, 10, 17, 20, 
    28, 37, 42, 87, 169, 
    428, 456, 632, 744, 
    766, 769, 780, 987, 
    8502, 8934, 13001, 
    191524, 191738096, 
    195864652, 308651098, 
    2249696156, 2938670577, 
    3635933258, 4130305148
]
tree_max_depths = []
number_of_simulations = 30
aggregation_strategies = ["all_trees", "threshold_trees", "merge_trees"]
number_of_clients_for_test = 20
start_ID_for_clients = 0
dirichlet_alpha = 0.1
number_of_bins_for_dirichlet = 100

[[simulation.epsilon_settings]]
epsilon = -1.0
balancing_coefficient = 0.37
threshold_value = 8941.4476
threshold_type = "mse"
threshold_multiplier = 1.001

[[simulation.epsilon_settings]]
epsilon = 10.0
balancing_coefficient = 0.37
threshold_value = 10129.0241
threshold_type = "mse"
threshold_multiplier = 1.001

[[simulation.epsilon_settings]]
epsilon = 7.0
balancing_coefficient = 0.37
threshold_value = 10162.7114
threshold_type = "mse"
threshold_multiplier = 1.001

[[simulation.epsilon_settings]]
epsilon = 5.0
balancing_coefficient = 0.37
threshold_value = 10282.4519
threshold_type = "mse"
threshold_multiplier = 1.001

[[simulation.epsilon_settings]]
epsilon = 3.0
balancing_coefficient = 0.37
threshold_value = 10303.8574
threshold_type = "mse"
threshold_multiplier = 1.001

[[simulation.epsilon_settings]]
epsilon = 1.0
balancing_coefficient = 0.37
threshold_value = 10507.1693
threshold_type = "mse"
threshold_multiplier = 1.001

[[simulation.epsilon_settings]]
epsilon = 0.75
balancing_coefficient = 0.37
threshold_value = 10694.6269
threshold_type = "mse"
threshold_multiplier = 1.001

[[simulation.epsilon_settings]]
epsilon = 0.5
balancing_coefficient = 0.37
threshold_value = 11082.4359
threshold_type = "mse"
threshold_multiplier = 1.001

[[simulation.epsilon_settings]]
epsilon = 0.25
balancing_coefficient = 0.37
threshold_value = 10981.8261
threshold_type = "mse"
threshold_multiplier = 1.001

[[simulation.epsilon_settings]]
epsilon = 0.1
balancing_coefficient = 0.37
threshold_value = 11172.5482
threshold_type = "mse"
threshold_multiplier = 1.001