[paths]
base_path = '.'
results_folder = 'results'
final_results_folder = 'final_results'
logs_folder = 'logs'
dataset_path = 'energydata_complete.csv'
graphics_path = 'graphics'

[settings]
number_of_jobs = 12
number_of_clients = 2
number_of_rounds = 40
seed = 42
aggregation_strategy = "random"

[settings.differential_privacy]
splitter = "best"
global_max_target = 1200
global_min_target = 0
tree_max_depth = 4
epsilon = 3.0
balancing_coefficient = 0.37

[settings.client]
timeout = 420
evaluate_type = "mse"

[settings.server]
IP = "0.0.0.0"
port = "50051"
pearson_threshold = 0.3
mean_squared_error_threhsold = 0
threshold_type = "pearson"
validate_dataset_size = 1000
print_every_trees_sent = 50
timeout = 360

[dataset]
train_test_split_size = 0.25
percentage_value_of_samples_per_client = 20

[scripts]
network_interface = "eth0"