syntax = "proto3";

package fedT;

import "google/protobuf/wrappers.proto";

service FedT {
    rpc aggregate_trees (Client_Tree) returns (stream Forest_Server);
    rpc get_server_model (Request_Server) returns (stream Forest_Server);
    rpc get_server_settings (Request_Server) returns (Server_Settings);
    rpc end_of_transmission (Request_End) returns (OK);
}

message Request_Server {
    uint32 client_ID = 1;
}

message Server_Settings {
    uint32 current_round = 1;
    google.protobuf.Int32Value seed = 2;
    float epsilon = 3;
}

message Client_Tree {
    uint32 client_ID = 1;
    bytes serialised_tree = 2;
}

message Forest_Server {
    bytes serialised_tree = 1;
}

message Request_End {
    uint32 client_ID = 1;
    uint32 client_tree_size = 2;
    uint32 server_tree_size = 3;
    double fit_time = 4;
    double initial_mse = 5;
    double initial_pearson = 6;
    double final_mse = 7;
    double final_pearson = 8;
    double round_time = 9;
    double round_start_time = 10; 
    double round_end_time = 11;
    double evaluate_time = 12;
    double inference_time = 13;
}

message OK {
    bool ok = 1;
}