"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import wrappers_pb2 as _wrappers_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Request_Server(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    client_ID: _builtins.int
    def __init__(
        self,
        *,
        client_ID: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_ID", b"client_ID"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Request_Server: _TypeAlias = Request_Server  # noqa: Y015

@_typing.final
class Server_Settings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CURRENT_ROUND_FIELD_NUMBER: _builtins.int
    SEED_FIELD_NUMBER: _builtins.int
    EPSILON_FIELD_NUMBER: _builtins.int
    current_round: _builtins.int
    epsilon: _builtins.float
    @_builtins.property
    def seed(self) -> _wrappers_pb2.Int32Value: ...
    def __init__(
        self,
        *,
        current_round: _builtins.int = ...,
        seed: _wrappers_pb2.Int32Value | None = ...,
        epsilon: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["seed", b"seed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["current_round", b"current_round", "epsilon", b"epsilon", "seed", b"seed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Server_Settings: _TypeAlias = Server_Settings  # noqa: Y015

@_typing.final
class Client_Tree(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    SERIALISED_TREE_FIELD_NUMBER: _builtins.int
    client_ID: _builtins.int
    serialised_tree: _builtins.bytes
    def __init__(
        self,
        *,
        client_ID: _builtins.int = ...,
        serialised_tree: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_ID", b"client_ID", "serialised_tree", b"serialised_tree"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Client_Tree: _TypeAlias = Client_Tree  # noqa: Y015

@_typing.final
class Forest_Server(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERIALISED_TREES_FIELD_NUMBER: _builtins.int
    serialised_trees: _builtins.bytes
    def __init__(
        self,
        *,
        serialised_trees: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["serialised_trees", b"serialised_trees"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Forest_Server: _TypeAlias = Forest_Server  # noqa: Y015

@_typing.final
class OK(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OK_FIELD_NUMBER: _builtins.int
    ok: _builtins.bool
    def __init__(
        self,
        *,
        ok: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ok", b"ok"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OK: _TypeAlias = OK  # noqa: Y015
