"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import wrappers_pb2 as _wrappers_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Request_Server(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    client_ID: _builtins.int
    def __init__(
        self,
        *,
        client_ID: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_ID", b"client_ID"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Request_Server: _TypeAlias = Request_Server  # noqa: Y015

@_typing.final
class Server_Settings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CURRENT_ROUND_FIELD_NUMBER: _builtins.int
    SEED_FIELD_NUMBER: _builtins.int
    EPSILON_FIELD_NUMBER: _builtins.int
    current_round: _builtins.int
    epsilon: _builtins.float
    @_builtins.property
    def seed(self) -> _wrappers_pb2.Int32Value: ...
    def __init__(
        self,
        *,
        current_round: _builtins.int = ...,
        seed: _wrappers_pb2.Int32Value | None = ...,
        epsilon: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["seed", b"seed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["current_round", b"current_round", "epsilon", b"epsilon", "seed", b"seed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Server_Settings: _TypeAlias = Server_Settings  # noqa: Y015

@_typing.final
class Client_Tree(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    SERIALISED_TREE_FIELD_NUMBER: _builtins.int
    client_ID: _builtins.int
    serialised_tree: _builtins.bytes
    def __init__(
        self,
        *,
        client_ID: _builtins.int = ...,
        serialised_tree: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_ID", b"client_ID", "serialised_tree", b"serialised_tree"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Client_Tree: _TypeAlias = Client_Tree  # noqa: Y015

@_typing.final
class Forest_Server(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SERIALISED_TREE_FIELD_NUMBER: _builtins.int
    serialised_tree: _builtins.bytes
    def __init__(
        self,
        *,
        serialised_tree: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["serialised_tree", b"serialised_tree"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Forest_Server: _TypeAlias = Forest_Server  # noqa: Y015

@_typing.final
class Request_End(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: _builtins.int
    CLIENT_TREE_SIZE_FIELD_NUMBER: _builtins.int
    SERVER_TREE_SIZE_FIELD_NUMBER: _builtins.int
    FIT_TIME_FIELD_NUMBER: _builtins.int
    INITIAL_MSE_FIELD_NUMBER: _builtins.int
    INITIAL_PEARSON_FIELD_NUMBER: _builtins.int
    FINAL_MSE_FIELD_NUMBER: _builtins.int
    FINAL_PEARSON_FIELD_NUMBER: _builtins.int
    ROUND_TIME_FIELD_NUMBER: _builtins.int
    ROUND_START_TIME_FIELD_NUMBER: _builtins.int
    ROUND_END_TIME_FIELD_NUMBER: _builtins.int
    EVALUATE_TIME_FIELD_NUMBER: _builtins.int
    INFERENCE_TIME_FIELD_NUMBER: _builtins.int
    client_ID: _builtins.int
    client_tree_size: _builtins.int
    server_tree_size: _builtins.int
    fit_time: _builtins.float
    initial_mse: _builtins.float
    initial_pearson: _builtins.float
    final_mse: _builtins.float
    final_pearson: _builtins.float
    round_time: _builtins.float
    round_start_time: _builtins.float
    round_end_time: _builtins.float
    evaluate_time: _builtins.float
    inference_time: _builtins.float
    def __init__(
        self,
        *,
        client_ID: _builtins.int = ...,
        client_tree_size: _builtins.int = ...,
        server_tree_size: _builtins.int = ...,
        fit_time: _builtins.float = ...,
        initial_mse: _builtins.float = ...,
        initial_pearson: _builtins.float = ...,
        final_mse: _builtins.float = ...,
        final_pearson: _builtins.float = ...,
        round_time: _builtins.float = ...,
        round_start_time: _builtins.float = ...,
        round_end_time: _builtins.float = ...,
        evaluate_time: _builtins.float = ...,
        inference_time: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_ID", b"client_ID", "client_tree_size", b"client_tree_size", "evaluate_time", b"evaluate_time", "final_mse", b"final_mse", "final_pearson", b"final_pearson", "fit_time", b"fit_time", "inference_time", b"inference_time", "initial_mse", b"initial_mse", "initial_pearson", b"initial_pearson", "round_end_time", b"round_end_time", "round_start_time", b"round_start_time", "round_time", b"round_time", "server_tree_size", b"server_tree_size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Request_End: _TypeAlias = Request_End  # noqa: Y015

@_typing.final
class OK(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OK_FIELD_NUMBER: _builtins.int
    ok: _builtins.bool
    def __init__(
        self,
        *,
        ok: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ok", b"ok"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OK: _TypeAlias = OK  # noqa: Y015
